# Generated by Django 4.0.6 on 2022-09-03 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='create_user',
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
